
name: Sync Fork

on:
  schedule:
    - cron: '0 0 1 * *'  # Corre no dia 1 de cada mês à meia-noite UTC
  workflow_dispatch:     # Permite correr manualmente

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Sync with upstream
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git clone https://github.com/${{ github.repository }} repo
          cd repo
          git remote add upstream https://github.com/massgravel/Microsoft-Activation-Scripts.git
          git fetch upstream
          git checkout main
          git merge upstream/main
          git push origin main
